image::https://classroom.github.com/assets/open-in-vscode-2e0aaae1b6195c2367325f4f02e2d04e9abb55f0b24a779b69b11b9e10269abc.svg["Open in Visual Studio Code", link="https://classroom.github.com/online_ide?assignment_repo_id=16973566&assignment_repo_type=AssignmentRepo"]

= S3.A.01 - Développement appli 2024-2025

:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b11

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------



WARNING: Ce dépôt présente le projet à développer dans le cadre de la S3.A.01 - Développement appli du BUT2 Informatique de l'IUT de Blagnac.

toc::[]

== Equipe

Projet est réalisé par::
- https://github.com/Ssauth[Thomas Aussenac] (Scrum master)
- https://github.com/Joan-arch[Joan Casas]
- https://github.com/Laloix23[Loïc Phrakousonh] 
- https://github.com/AMAYZING31[Sidney Richards]
- https://github.com/ylaghdas[Yassine Laghdas] (Product Owner)

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB] et mailto:esther.pendaries@univ-tlse2.fr[EP]

== Réalisations 

TIP: Mettez ici toutes les informations nécessaire à l'utilisation de votre dépôt (comment on installe votre application, où sont les docs, etc.)

== Présentation de notre client : Simul8

Simul8 est une entreprise spécialisée dans la production de maquettes à taille réelle, non fonctionnelles, mais extrêmement réalistes. Elle s’adresse principalement à des particuliers souhaitant posséder des objets rares ou coûteux sous forme de répliques abordables, ainsi qu’à des professionnels du cinéma ou du théâtre recherchant des décors à moindre coût. Leur slogan : "Fake it till you make it".

=== Origines et Mission

Fondée en 1999 par Matthias Lionardo, Simul8 est née d’une passion pour le bricolage et la création d’objets inaccessibles. L’entreprise, initialement basée dans le sud de la France, aspire aujourd'hui à se développer via sa nouvelle boutique en ligne.

=== Équipe Dirigeante

- Matthias Lionardo - PDG et fondateur
- Lohan Serre - Directeur Général
- Chefai Tristan - Directeur Marketing et Artistique
- Ethan Besse - Directeur Logistique


== Gestion de projet & Qualité

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b11/releases/tag/v0.0.3[v0.0.3]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- Lien vers le backlog du sprint : https://github.com/orgs/IUT-Blagnac/projects/262/views/1
- Lien vers la doc de Conception : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b11/blob/master/doc/docConception.adoc
- Lien vers le product backlog : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b11/labels/User%20Story
- Tests unitaires et plans de test : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b11/blob/master/doc/docTest.adoc
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application

Prochaine release le 24/11/2024

Voici un exemple d'évaluation :

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image"></iframe>
++++
endif::[]
