image::https://classroom.github.com/assets/open-in-vscode-2e0aaae1b6195c2367325f4f02e2d04e9abb55f0b24a779b69b11b9e10269abc.svg["Open in Visual Studio Code", link="https://classroom.github.com/online_ide?assignment_repo_id=16973566&assignment_repo_type=AssignmentRepo"]

= S3.A.01 - Développement appli 2024-2025

:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b11

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------



WARNING: Ce dépôt présente le projet à développer dans le cadre de la S3.A.01 - Développement appli du BUT2 Informatique de l'IUT de Blagnac.

toc::[]

== Equipe

Projet est réalisé par::
- https://github.com/Ssauth[Thomas Aussenac] (Scrum master)
- https://github.com/Joan-arch[Joan Casas]
- https://github.com/Laloix23[Loïc Phrakousonh] 
- https://github.com/AMAYZING31[Sidney Richards]
- https://github.com/ylaghdas[Yassine Laghdas] (Product Owner)

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB] et mailto:esther.pendaries@univ-tlse2.fr[EP]

== Réalisations 

TIP: Mettez ici toutes les informations nécessaire à l'utilisation de votre dépôt (comment on installe votre application, où sont les docs, etc.)

== Présentation de notre client : Simul8

Simul8 est une entreprise spécialisée dans la production de maquettes à taille réelle, non fonctionnelles, mais extrêmement réalistes. Elle s’adresse principalement à des particuliers souhaitant posséder des objets rares ou coûteux sous forme de répliques abordables, ainsi qu’à des professionnels du cinéma ou du théâtre recherchant des décors à moindre coût. Leur slogan : "Fake it till you make it".

=== Origines et Mission

Fondée en 1999 par Matthias Lionardo, Simul8 est née d’une passion pour le bricolage et la création d’objets inaccessibles. L’entreprise, initialement basée dans le sud de la France, aspire aujourd'hui à se développer via sa nouvelle boutique en ligne.

=== Équipe Dirigeante

- Matthias Lionardo - PDG et fondateur
- Lohan Serre - Directeur Général
- Chefai Tristan - Directeur Marketing et Artistique
- Ethan Besse - Directeur Logistique
- Matteo Pellegatta - Chef departement


== Gestion de projet & Qualité

- Version courante : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b11/releases/tag/v0.0.6[v0.0.6]
- Lien vers la doc technique
- Lien vers la doc utilisateur
- https://github.com/orgs/IUT-Blagnac/projects/262/views/1[Lien vers le backlog du sprint]
- link:doc/BD/docConception.adoc[Lien vers la doc de Conception] 
- link:https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b11/issues?q=is%3Aopen+is%3Aissue+label%3A%22User+Story%22[Lien vers le product backlog]
- link:doc/PHP/cahier_de_recette.adoc[Lien vers le cahier de recette] 
- link:doc/PHP/schema_denchainement_des_pages.png[Lien vers le schéma d'enchainement des pages]
- link:doc/réunions/ODJ_06-12-2024_G2B11.pdf[Lien vers l'ODJ du 06/12/2024 (Semaine 49)] 
- link:doc/réunions/CR_06_12-2024_G2B11.pdf[Lien vers le CR du 06/12/2024 (Semaine 49)]
- link:doc/réunions/Sprint6_ODJ%2BCR%2BAnalyse_Equipedev_2B.pdf[Lien vers l'ODJ, le CR et l'Analyse du 09/12/2024 (Semaine 50)]
- link:doc/r%C3%A9unions/Sprint7_ODJ_G2B11.pdf[Lien vers l'ODJ du 19/12/2024 (Semaine 51)]
- link:doc/réunions/Sprint7_CR%2BAnalyse_G2B11.pdf[Lien vers le Compte Rendu et l'analyse du sprint 7 du 19/12/2024 (Semaine 51)]
- https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b11/blob/master/doc/droit/Fiche%20de%20Conseils%20Juridiques%20et%20de%20S%C3%A9curit%C3%A9%20-%20Simul8.pdf[Fiche de Conseils Juridiques et de Sécurité]


Prochaine release le 16/12/2024

== Evaluation communication

=== Retour semaine 48

ODJ et CR non fait
Note 0/3

=== retour semaine 49
ODJ: Pb date ! Précisez la salle.  Précisez dans le plan qui est responsable de chaque item. CR: manque retour rdv client Web, manque analyse difficultés/ Réussites, manque futur responsable de la com semaine 50. 
note : 2,09/3
note appel offre : 13,37/20

=== retour semaine 50
ODJ :  manque qui est responsable de chaque thème mis à l'ordre du jour. Séparer ODJ de CR. CR : préciser clairement les présents. Il manque toujours le point client et l'analyse des difficultés et réussites techniques et organisationnelles.
note : 2/3

=== Voici un exemple d'évaluation :

image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image]

==== Sprint 2 :

image:https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=1287010292&format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=1287010292&format=image]

